//using System.ComponentModel.DataAnnotations.Schema;
//using System.ComponentModel.DataAnnotations;

//namespace InventoryManagementSystem.Models.Entity
//{
//    /// <summary>
//    /// Represents stock information for a product in the inventory management system.
//    /// </summary>
//    public class Stocks
//    {
//        /// <summary>
//        /// Unique identifier for the stock entry, auto-generated by the database.
//        /// </summary>
//        [Key]
//        public long StockId { get; set; }

//        /// <summary>
//        /// Identifier of the associated product.
//        /// </summary>
//        [Required]
//        public long ProductId { get; set; }

//        /// <summary>
//        /// Current quantity of the product available in stock.
//        /// </summary>
//        [Required]
//        public int AvailableQuantity { get; set; }

//        /// <summary>
//        /// Minimum required quantity of the product to maintain in stock.
//        /// </summary>
//        [Required]
//        public int MinimumRequiredQuantity { get; set; }

//        /// <summary>
//        /// Identifier of the user who created the stock entry.
//        /// </summary>
//        public long CreatedBy { get; set; }

//        /// <summary>
//        /// Date and time when the stock entry was created.
//        /// </summary>
//        public DateTime CreatedAt { get; set; }

//        /// <summary>
//        /// Identifier of the user who last updated the stock entry.
//        /// </summary>
//        public long UpdatedBy { get; set; }

//        /// <summary>
//        /// Date and time when the stock entry was last updated.
//        /// </summary>
//        public DateTime UpdatedAt { get; set; } = DateTime.Now;

//        /// <summary>
//        /// Status of the stock.
//        /// </summary>
//        public int StockStatusId { get; set; }

//        /// <summary>
//        /// Date and time when the stock was last restocked.
//        /// </summary>
//        public DateTime LastRestockAt { get; set; }

//        /// <summary>
//        /// The associated product entity.
//        /// </summary>
//        [ForeignKey("ProductId")]
//        public Products Product { get; set; }
//        [ForeignKey("CreatedBy")]
//        public Users CreatedByUser { get; set; }

//        //[ForeignKey("UpdatedBy")]
//        //public Users UpdatedByUser { get; set; }

//        [ForeignKey("StockStatusId")]
//        public StockStatus StockStatus { get; set; }

//    }
//}