using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace InventoryManagementSystem.Models.Entity;

public class VendorDetails
{
    /// <summary>
    /// Unique identifier for the vendor, auto-generated by the database.
    /// </summary>
    [Key]
    public long VendorId { get; set; }

    /// <summary>
    /// Name of the vendor (maximum 255 characters).
    /// </summary>
    [Required]
    [StringLength(50)]
    public string? Name { get; set; }

    /// <summary>
    /// Name of the vendor's store.
    /// </summary>
    [StringLength(100)]
    public string StoreName { get; set; }

    /// <summary>
    /// Phone number of the vendor (maximum 20 characters).
    /// </summary>
    [StringLength(15)]
    public string Phone { get; set; }

    /// <summary>
    /// Email address of the vendor (maximum 255 characters).
    /// </summary>
    [StringLength(100)]
    [EmailAddress]
    public string Email { get; set; }

    /// <summary>
    /// Address of the vendor (maximum 500 characters).
    /// </summary>
    [StringLength(500)]
    public string Address { get; set; }

    /// <summary>
    /// City of the vendor (maximum 100 characters).
    /// </summary>
    [StringLength(50)]
    public string City { get; set; }

    /// <summary>
    /// State of the vendor (maximum 100 characters).
    /// </summary>
    [StringLength(50)]
    public string State { get; set; }

    /// <summary>
    /// Country of the vendor (maximum 100 characters).
    /// </summary>
    [StringLength(50)]
    public string Country { get; set; }

    /// <summary>
    /// Postal code of the vendor (maximum 10 characters).
    /// </summary>
    [StringLength(10)]
    public string Pincode { get; set; }

    /// <summary>
    /// Identifier of the user who created the vendor record.
    /// </summary>
    public long CreatedBy { get; set; }

    /// <summary>
    /// Date and time when the vendor record was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// Identifier of the user who last updated the vendor record.
    /// </summary>
    public long UpdatedBy { get; set; }

    /// <summary>
    /// Date and time when the vendor record was last updated.
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// Indicates whether the vendor record is deleted.
    /// </summary>
    public bool IsDeleted { get; set; }

    [ForeignKey(nameof(CreatedBy))]
    public Users CreatedByUser { get; set; }

}